name: Build and Push Docker Image

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sukhvir097/mern-client:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull latest Docker image
        run: docker pull sukhvir097/mern-client:latest

      - name: Stop and remove existing container (if exists)
        run: |
          docker stop mern-client || true
          docker rm mern-client || true

      - name: Run new container
        run: |
          docker run -d \
            --name mern-client \
            -p 3000:80 \
            sukhvir097/mern-client:latest


